### PR TITLE
doc: Update DataFusion project name and url

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao @andygrove

**Review by kazuyukitanimura — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Thank you @kazuyukitanimura

**Review by sunchao — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
