### PR TITLE
feat: Improve CometBroadcastHashJoin statistics

### LINKED ISSUE #338: Improve CometBroadcastHashJoin statistics
### What is the problem the feature request solves?

Add all statistics HashJoinExec datafusion node provides.

### Describe the potential solution

Override metrics map in CometBroadcastHashJoin to provide all available metrics

### Additional context

**Current metrics:**
```
output_rows
Elapsed_compute
```
**All available metrics**
```
/// Total time for collecting build-side of join
pub(crate) build_time: metrics::Time
/// Number of batches consumed by build-side
pub(crate) build_input_batches: metrics::Count,
/// Number of rows consumed by build-side
pub(crate) build_input_rows: metrics::Count,
/// Memory used by build-side in bytes
pub(crate) build_mem_used: metrics::Gauge,
/// Total time for joining probe-side batches to the build-side batches
pub(crate) join_time: metrics::Time,
/// Number of batches consumed by probe-side of this operator
pub(crate) input_batches: metrics::Count,
/// Number of rows consumed by probe-side this operator
pub(crate) input_rows: metrics::Count,
/// Number of batches produced by this operator
pub(crate) output_batches: metrics::Count,
/// Number of rows produced by this operator
pub(crate) output_rows: metrics::Count
```

### PR DESCRIPTION
**Pull request by planga82**
## Which issue does this PR close?

Closes #338 .

## Rationale for this change

Add all statistics HashJoinExec datafusion node provides.

## What changes are included in this PR?

All available metrics
```
/// Total time for collecting build-side of join
pub(crate) build_time: metrics::Time
/// Number of batches consumed by build-side
pub(crate) build_input_batches: metrics::Count,
/// Number of rows consumed by build-side
pub(crate) build_input_rows: metrics::Count,
/// Memory used by build-side in bytes
pub(crate) build_mem_used: metrics::Gauge,
/// Total time for joining probe-side batches to the build-side batches
pub(crate) join_time: metrics::Time,
/// Number of batches consumed by probe-side of this operator
pub(crate) input_batches: metrics::Count,
/// Number of rows consumed by probe-side this operator
pub(crate) input_rows: metrics::Count,
/// Number of batches produced by this operator
pub(crate) output_batches: metrics::Count,
/// Number of rows produced by this operator
pub(crate) output_rows: metrics::Count
```
image

## How are these changes tested?

Unit testing and manual testing

### CODE REVIEW

**Comment by planga82** [comment]
It seems that there are problems in tests with Spark 3.3 and Spark 3.2. I'm checking it out.

**Comment by planga82** [comment]
Fix tested in my repository with github actions

**Review by viirya — APPROVED** [review]
Thanks @planga82

**Review by kazuyukitanimura — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks @planga82 @kazuyukitanimura

**Pull request merged**
