### PR TITLE
chore: Make COMET_EXEC_BROADCAST_FORCE_ENABLED internal config

### LINKED ISSUE #408: bug: TPC-H q16 failed with "ColumnarToRow does not implement doExecuteBroadcast"
### Describe the bug

I am benchmarking locally with small scale factor (100GB) and saw q16 fail.

Debug logging showed some reasons we can't support this query natively:

```
WARN CometSparkSessionExtensions$CometExecRule: Comet cannot execute this plan natively because:
        - BuildRight is not supported
        - Native shuffle is not enabled
```

The query failed at runtime:

```
org.apache.spark.SparkUnsupportedOperationException: ColumnarToRow does not implement doExecuteBroadcast.
```

I used these Comet configs:

```
        command.append("--jars $COMET_JAR")
        command.append("--conf spark.sql.extensions=org.apache.comet.CometSparkSessionExtensions")
        command.append("--conf spark.comet.enabled=true")
        command.append("--conf spark.comet.explainFallback.enabled=true")
        command.append("--conf spark.comet.exec.enabled=true")
        command.append("--conf spark.comet.exec.all.enabled=true")
        command.append("--conf spark.comet.exec.all.expr.enabled=true")
        command.append("--conf spark.comet.exec.shuffle.enabled=true")
        command.append("--conf spark.comet.exec.broadcast.enabled=true")
        command.append("--conf spark.comet.columnar.shuffle.enabled=true")
        command.append("--conf spark.comet.cast.allowIncompatible=true")
        command.append("--conf spark.shuffle.manager=org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager")
        command.append("--conf spark.driver.extraClassPath=$COMET_JAR")
        command.append("--conf spark.executor.extraClassPath=$COMET_JAR")
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #408.

### CODE REVIEW

**Comment by viirya** [comment]
cc @andygrove

**Review by comphead — APPROVED** [review]
lgtm thanks @viirya 
should we also modify the text saying this param is internal?

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
> lgtm thanks @viirya should we also modify the text saying this param is internal?

I don't think we need to change the description of the config. We just need to make it internal so that it doesn't appear in the public documentation.

**Comment by viirya** [comment]
> I don't think we need to change the description of the config. We just need to make it internal so that it doesn't appear in the public documentation.

Yes, I agreed. Thanks @andygrove @comphead

**Pull request merged**
