### PR TITLE
fix: Optimize decimal creation macros

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Part of #679 and #670

## Rationale for this change

This PR improves decimal creation macros

## What changes are included in this PR?

Consolidated make_plain_decimal_impl to make_int_decimal_variant_impl

## How are these changes tested?

Existing tests

### CODE REVIEW

**Comment by kazuyukitanimura** [comment]
```
OpenJDK 64-Bit Server VM 17.0.11+9-LTS on Mac OS X 14.5
Apple M1 Max
TPCDS Micro Benchmarks:                   Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
q44                                                2156           2293         157        133.7           7.5       1.0X
q44: Comet (Scan)                                  1968           2068         102        146.5           6.8       1.1X
q44: Comet (Scan, Exec)                            2264           2343          50        127.3           7.9       1.0
```

**Comment by kazuyukitanimura** [comment]
### Before
Screenshot 2024-08-01 at 11 22 56 PM

### After
Screenshot 2024-08-01 at 11 23 16 PM

**Comment by kazuyukitanimura** [comment]
@andygrove @comphead @huaxingao @parthchandra @viirya

**Review by andygrove — APPROVED** [review]
Screenshot from 2024-08-05 15-56-33

:+1: 

Consolidating the macros makes sense to me. Thanks @kazuyukitanimura.

**Pull request merged**
