### PR TITLE
fix: Optimize not to call getNullCount as much as possible

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Rationale for this change

This PR reduces to call getNullCount as much as possible

## What changes are included in this PR?

Calling getNullCount is expensive so reusing the number rather than re-calculating

## How are these changes tested?

Existing test

### CODE REVIEW

**Comment by kazuyukitanimura** [comment]
### Before
Screenshot 2024-08-13 at 3 22 53 PM

### After
Screenshot 2024-08-13 at 3 22 38 PM

**Comment by kazuyukitanimura** [comment]
@andygrove @comphead @huaxingao @parthchandra @viirya

**Comment by kazuyukitanimura** [comment]
Somehow `Run codecov/codecov-action@v3` keeps failing, seems not related but not sure why

**Comment by andygrove** [comment]
I am now running benchmarks with this PR

**Comment by andygrove** [comment]
I ran my local TPC-DS benchmark and it doesn't show any improvement for that benchmark. 

tpcds_allqueries (4)

@kazuyukitanimura Do you see an improvement with any of the microbenchmark queries?

**Comment by kazuyukitanimura** [comment]
Thanks @andygrove 
hmmm how many iteration was used for your local benchmark?

I used q27. 
I will try to run some microbenchmarks to showcase...

**Comment by kazuyukitanimura** [comment]
@andygrove I ran q27 30 times. The improvement is not as big as I hoped but it is improving

### Before
```
OpenJDK 64-Bit Server VM 17.0.11+9-LTS on Mac OS X 14.6.1
Apple M1 Max
TPCDS Micro Benchmarks:                   Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
q27: Comet (Scan, Exec)                            4001           4183          98         72.5          13.8       1.0X
```

### After
```
OpenJDK 64-Bit Server VM 17.0.11+9-LTS on Mac OS X 14.6.1
Apple M1 Max
TPCDS Micro Benchmarks:                   Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
q27: Comet (Scan, Exec)                            3847           4104         122         75.4          13.3       1.0X
```

**Review by andygrove — APPROVED** [review]
Thanks @kazuyukitanimura

**Comment by kazuyukitanimura** [comment]
Thanks, I realized there might be a better way to do this. Please hold merging.

**Comment by kazuyukitanimura** [comment]
opened https://github.com/apache/datafusion-comet/pull/1055 instead

**Pull request closed without merging**
