### PR TITLE
chore: Change maven group id from org.apache.comet to org.apache.datafusion.comet

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

N/A

## Rationale for this change

The Maven group ID of `org.apache.comet` implies that Comet is a top-level Apache project, and this could cause confusion.

## What changes are included in this PR?

Change the group ID to `org.apache.datafusion.comet` to reflect the fact that Comet is a subproject of the Apache DataFusion top-level project (at least, it will be in the next week or so).

We should also change the Java package names, but I would prefer that we do this as a separate PR.

## How are these changes tested?

Existing tests.

### CODE REVIEW

**Comment by andygrove** [comment]
@snmvaughan fyi

**Comment by sunchao** [comment]
I don't have strong opinion on this. It does mean, however, _if_ Comet becomes a top-level project in future, we'd do a costly renaming again which could affect users of the library.

**Review by comphead — APPROVED** [review]
lgtm thanks @andygrove

**Comment by parthchandra** [comment]
Are we planning to rename the package names as well?

**Comment by viirya** [comment]
> Are we planning to rename the package names as well?

I don't think it is really necessary though, but not a strong opinion.

**Comment by andygrove** [comment]
I am going to backtrack on this and close this issue.

If we are clear about the project's goals to one day graduate from the Apache DataFusion project, then I think it is fine to use `org.apache.comet` for package names and keep the current maven packaging. This would match what the Apache Gluten(incubating) project is doing.

Thanks for the reviews and feedback.

**Pull request closed without merging**
