### PR TITLE
[WIP] Add spark 35

### PR DESCRIPTION
**Pull request by holdenk**
## Which issue does this PR close?

Adds Spark 3.5

## Rationale for this change

Spark 3.5 is the latest Spark release.

## What changes are included in this PR?

Adds Spark 3.5 support, this introduces a new per-spark version of shims as part of adding interfacing to the 3.5 APIs.
This has the advantage of static compile checks over the existing shim approach which does reflection for everything, but I can switch to the runtime reflection model for consistency if that's preferred.

## How are these changes tested?

WIP

### CODE REVIEW

**Comment by wankunde** [comment]
Some class and function has changed in spark 3.5, maybe we need some more shim classes to support both spark 3.5 and the versions before.

I has a similar commit to do this:
https://github.com/apache/arrow-datafusion-comet/commit/b038267eb5e6ddafccf84b0147760f6992f36077

**Comment by holdenk** [comment]
Yup this adds some shims (there are existing shims too for 3.3 etc but they use reflection heavily).

**Comment by sunchao** [comment]
FWIW I created https://github.com/apache/arrow-datafusion-comet/issues/140 to improve the current Spark shim handling.

**Comment by holdenk** [comment]
I love it :)

**Comment by kazuyukitanimura** [comment]
FYI https://github.com/apache/datafusion-comet/pull/318 is just merged

**Comment by andygrove** [comment]
Thanks for getting this started @holdenk. I have now created https://github.com/apache/datafusion-comet/pull/587 to add experimental support for Spark 3.5.1 (there will be follow up PRs to fix some test failures), so will close this one.

**Pull request closed without merging**
