### PR TITLE
fix: Fallback to Spark for unsupported input besides ordering

### LINKED ISSUE #769: Fallback to Spark for unsupported input besides ordering
### Describe the bug

This is also a regression brought by #760. Besides shuffle expressions/orderings, we still need to check input types.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #769.

### CODE REVIEW

**Review by huaxingao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Thank you @huaxingao

**Review by kazuyukitanimura — APPROVED** [review]
Pending CI

**Comment by viirya** [comment]
Thanks @huaxingao @kazuyukitanimura

**Pull request merged**
