### PR TITLE
feat: Add ShuffleQueryStageExec to direct child node for CometBroadcastExchangeExec

### LINKED ISSUE #879: ShuffleQueryStageExec could be direct child node of CometBroadcastExchangeExec
### Describe the bug

We found an issue internally where `ShuffleQueryStageExec` becomes direct node of `CometBroadcastExchangeExec` but it doesn't allow for now:

```
- ShuffleQueryStageExec could be direct child node of CometBroadcastExchangeExec *** FAILED *** (6 seconds, 287 milliseconds)                                                                                                          
  org.apache.comet.CometRuntimeException: Child of CometBroadcastExchangeExec should be CometExec, but got: class org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec                                                        
  at org.apache.spark.sql.comet.CometBroadcastExchangeExec.$anonfun$relationFuture$1(CometBroadcastExchangeExec.scala:149)                                                                                                             
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:217)       
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                                                                                
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                                                                         
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                                                                         
  at java.base/java.lang.Thread.run(Thread.java:833)                                                                                                                                                                                   
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #879.

### CODE REVIEW

**Comment by viirya** [comment]
cc @huaxingao

**Review by huaxingao — APPROVED** [review]
LGTM. Thanks @viirya

**Comment by huaxingao** [comment]
Merged. Thanks @viirya

**Comment by viirya** [comment]
Thank you @huaxingao

**Pull request merged**
