### PR TITLE
chore: Enable Comet shuffle with AQE coalesce partitions

### LINKED ISSUE #387: Enable Comet shuffle with AQE coalesce partitions
### What is the problem the feature request solves?

We are going to disable Comet shuffle if AQE coalesce partitions is enabled due to potential memory leak issue on Java Arrow StreamReader (#380).

We should address this issue and fix it to enable Comet shuffle with AQE coalesce partitions.

### Describe the potential solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #387.

### CODE REVIEW

**Comment by viirya** [comment]
This is a copy of #651 but removed some changes. I'd like to see if "os cannot spawn new native thread" error could be removed.

And I also want to check if core-1 can pass without these changes on ubuntu-24.04.

**Comment by viirya** [comment]
After changing to ubuntu 24.04, the negative ref count error like following disappears on Spark 3.4.3, although it still happens on Spark 4.0.0 and Spark 3.5.1. 

Note that it only happens on `spark-sql-sql/core-1`, other Spark SQL tests are passed.


```
[info]   		Suppressed: java.lang.IllegalStateException: RefCnt has gone negative
[info]   			at org.apache.comet.shaded.arrow.util.Preconditions.checkState(Preconditions.java:465)
[info]   			at org.apache.comet.shaded.arrow.memory.BufferLedger.release(BufferLedger.java:131)
[info]   			at org.apache.comet.shaded.arrow.memory.BufferLedger.release(BufferLedger.java:105)
[info]   			at org.apache.comet.shaded.arrow.vector.BaseValueVector.releaseBuffer(BaseValueVector.java:114)
[info]   			at org.apache.comet.shaded.arrow.vector.BaseFixedWidthVector.clear(BaseFixedWidthVector.java:248)
[info]   			at org.apache.comet.shaded.arrow.vector.BaseFixedWidthVector.close(BaseFixedWidthVector.java:238)
[info]   			at org.apache.comet.vector.CometVector.close(CometVector.java:210)```

**Comment by viirya** [comment]
As it cannot be reproduced locally and on internal CI, I'm going to disable columnar shuffle in `spark-sql-sql/core-1` for Spark 4.0.0 and Spark 3.5.1 temporarily. We can revisit this issue once we find a certain way to reproduce it.

**Comment by viirya** [comment]
For Spark 3.4.3, it is also probably negative ref count error happening on `core-1` (e.g., in last run). So I disabled Comet shuffle for it too.

**Review by andygrove — APPROVED** [review]
LGTM. Thank you @viirya!

**Comment by viirya** [comment]
Thanks @andygrove

**Pull request merged**
