### PR TITLE
fix: Normalize NaN and zeros for floating number comparison

### LINKED ISSUE #663: Comparison between negative zero and false produces incorrect result
## SQL
```
SELECT c30, c98, c30 = c98 FROM test0 ORDER BY c30, c98;
```
### Spark Plan
```
AdaptiveSparkPlan isFinalPlan=true
+- == Final Plan ==
   *(2) Sort [c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST], true, 0
   +- AQEShuffleRead coalesced
      +- ShuffleQueryStage 0
         +- Exchange rangepartitioning(c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, [plan_id=16892]
            +- *(1) Project [c30#30, c98#98, (c30#30 = cast(c98#98 as float)) AS (c30 = c98)#15740]
               +- *(1) ColumnarToRow
                  +- FileScan parquet [c30#30,c98#98] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c30:float,c98:boolean>
+- == Initial Plan ==
   Sort [c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST], true, 0
   +- Exchange rangepartitioning(c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, [plan_id=16878]
      +- Project [c30#30, c98#98, (c30#30 = cast(c98#98 as float)) AS (c30 = c98)#15740]
         +- FileScan parquet [c30#30,c98#98] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c30:float,c98:boolean>

```
### Comet Plan
```
AdaptiveSparkPlan isFinalPlan=true
+- == Final Plan ==
   *(2) Sort [c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST], true, 0
   +- AQEShuffleRead coalesced
      +- ShuffleQueryStage 0
         +- Exchange rangepartitioning(c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, [plan_id=16957]
            +- *(1) ColumnarToRow
               +- CometProject [c30#30, c98#98, (c30 = c98)#15748], [c30#30, c98#98, (c30#30 = cast(c98#98 as float)) AS (c30 = c98)#15748]
                  +- CometScan parquet [c30#30,c98#98] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c30:float,c98:boolean>
+- == Initial Plan ==
   Sort [c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST], true, 0
   +- Exchange rangepartitioning(c30#30 ASC NULLS FIRST, c98#98 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, [plan_id=16937]
      +- CometProject [c30#30, c98#98, (c30 = c98)#15748], [c30#30, c98#98, (c30#30 = cast(c98#98 as float)) AS (c30 = c98)#15748]
         +- CometScan parquet [c30#30,c98#98] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c30:float,c98:boolean>

```
First difference at row 23:
Spark: `-0.0,false,true`
Comet: `-0.0,false,false`

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #663.

### CODE REVIEW

**Comment by kazuyukitanimura** [comment]
Related https://github.com/apache/datafusion-comet/pull/585

**Review by andygrove — APPROVED** [review]
LGTM! I ran TPC-H and saw no regression. Thanks @viirya

**Comment by andygrove** [comment]
@viirya Should  there be any update to the documentation, such as the compatibility guide as part of this PR?

**Comment by viirya** [comment]
> @viirya Should there be any update to the documentation, such as the compatibility guide as part of this PR?

Good suggestion. Let me add one.

**Comment by viirya** [comment]
Thanks @andygrove

**Pull request merged**
