### PR TITLE
feat: Support spark base64 function

### LINKED ISSUE #419: Support spark base64 function
### What is the problem the feature request solves?

Support spark base64 function

### Describe the potential solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoluan2009**
## Which issue does this PR close?

Closes #419 .

### CODE REVIEW

**Comment by leoluan2009** [comment]
@viirya Help to start CI, thanks

**Comment by leoluan2009** [comment]
@viirya help to start CI and review code, thanks

**Comment by viirya** [comment]
Looks like there are incompatible results compared with Spark.

**Comment by leoluan2009** [comment]
> Looks like there are incompatible results compared with Spark.

datafusion use Basic type of base64 scheme while spark use MIME type. After search the source of  https://github.com/marshallpierce/rust-base64 which is used by datafusion for base64 function, I found this lib do not support MIME type of base64 scheme, so it may difficult to add Spark-compatible base64/unbase64 function. @viirya  do you have some good ideas？

**Comment by viirya** [comment]
Could we find another library supporting that? We can implement custom base64 function in Comet.

**Comment by leoluan2009** [comment]
> Could we find another library supporting that? We can implement custom base64 function in Comet.

I will do some research and have a try, thanks

**Pull request closed without merging**
