### PR TITLE
fix: Remove castting on decimals with a small precision to decimal256 

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Part of #670

## Rationale for this change

This PR improves the native execution performance on decimals with a small precision

## What changes are included in this PR?

This PR changes not to promote decimal128 to decimal256 if the precisions are small enough

## How are these changes tested?

Existing tests

### CODE REVIEW

**Comment by kazuyukitanimura** [comment]
```
OpenJDK 64-Bit Server VM 17.0.11+9-LTS on Mac OS X 14.5
Apple M1 Max
TPCDS Micro Benchmarks:                   Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
add_many_decimals                                 10883          11268         365         26.5          37.8       1.0X
add_many_decimals: Comet (Scan)                   13924          14097         309         20.7          48.3       0.8X
add_many_decimals: Comet (Scan, Exec)             12476          12570         111         23.1          43.3       0.9X
```

**Comment by andygrove** [comment]
I created a criterion benchmark for decimal_div inhttps://github.com/apache/datafusion-comet/pull/743.

The results look great for the changes in this PR.

```
decimal_div             time:   [5.3281 µs 5.3370 µs 5.3485 µs]
                        change: [-94.767% -94.727% -94.685%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by kazuyukitanimura** [comment]
@comphead @huaxingao @parthchandra  @viirya

**Review by andygrove — APPROVED** [review]
I'm not an expert on the decimal math in here, but all tests are passing, and performance is improved, so LGTM

**Comment by kazuyukitanimura** [comment]
Thank you @andygrove merged

**Pull request merged**
