### PR TITLE
fix: Unknown operator id when explain with formatted mode

### LINKED ISSUE #409: bug: unkown operator id for CometScanExec
### Describe the bug

unkown operator id for CometScanExec when execute explain with formatted mode:
`(unknown) Scan parquet tpch_spark_hdfs_parquet_snappy_1.lineitem`
`Output [7]: [l_partkey#7L, l_quantity#10, l_extendedprice#11, l_discount#12, l_shipinstruct#18, l_shipmode#19, l_shipdate#21]`

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoluan2009**
## Which issue does this PR close?

Closes #409 .

### CODE REVIEW

**Comment by leoluan2009** [comment]
@viirya @andygrove Help to start CI

**Comment by viirya** [comment]
Triggered.

**Review by comphead — COMMENTED** [review]
thanks @leoluan2009 
appreciate if you could add the unit test to prevent regression

**Comment by leoluan2009** [comment]
Can anyone help to find why some checks failed and  how  can I fix. @comphead @viirya

**Comment by comphead** [comment]
> Can anyone help to find why some checks failed and how can I fix. @comphead @viirya

TPCDS plans comparison failed, supposedly because of this change the plan representation changed and now failed when gets compared with static expected plans

**Comment by viirya** [comment]
You need to update plan stability results, including `CometTPCDSV1_4_PlanStabilitySuite` and `CometTPCDSV2_7_PlanStabilitySuite`.

**Comment by leoluan2009** [comment]
I have update plan stability results, can you help trigger CI?

**Comment by leoluan2009** [comment]
Ci failed because of connection timeout:

**Comment by leoluan2009** [comment]
> thanks @leoluan2009 appreciate if you could add the unit test to prevent regression

@comphead can you give me a example? thanks

**Comment by viirya** [comment]
> Ci failed because of connection timeout

I will re-trigger failed pipelines.

**Review by parthchandra — APPROVED** [review]
LGTM

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks @leoluan2009 @parthchandra @comphead

**Pull request merged**
