### PR TITLE
fix: Incorrect input schema when preparing result expressions for HashAggregation

### LINKED ISSUE #502: Incorrect input schema when preparing result expressions for HashAggregation
### Describe the bug

If there are result expressions for Spark HashAggregation, we prepare these physical expressions to add an additional DataFusion `ProjectionExec` on top of `AggregateExec`.

Currently we incorrectly use `AggregateExec`'s child schema as input schema to prepare these physical expressions. It causes some test failures in #403 as latest DataFusion adds additional check for that in https://github.com/apache/datafusion/pull/10088.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #502.

### CODE REVIEW

**Comment by viirya** [comment]
cc @huaxingao

**Comment by viirya** [comment]
cc @sunchao

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks @sunchao

**Pull request merged**
