### PR TITLE
build: Switch back to official DataFusion repo and arrow-rs after Arrow Java 16 is released

### LINKED ISSUE #248: Switch back to released version of DataFusion and arrow-rs after Arrow Java 16 is released
### What is the problem the feature request solves?

In #239, we moved to use specified forked of DataFusion and arrow-rs as a temporary workaround to the Arrow Java bug which sends invalid offset buffers through C Data Interface.

The fix to the bug was merged to Arrow Java. Once Arrow Java 16 is released, we should move back to released versions of DataFusion and arrow-rs.

### Describe the potential solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #248.

### CODE REVIEW

**Comment by viirya** [comment]
Note that this is blocked by #250. We need to verify Java Arrow after #250 is merged.

**Comment by viirya** [comment]
The fix (https://github.com/apache/datafusion/pull/10094) is not released yet. So the following error still happens in CI:

```
CometAggregateSuite:
- count with aggregation filter (371 milliseconds)
- lead/lag should return the default value if the offset row does not exist *** FAILED *** (133 milliseconds)
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 32.0 failed 1 times, most recent failure: Lost task 0.0 in stage 32.0 (TID 45) (74d216948a65 executor driver): org.apache.comet.CometNativeException: Arrow error: Invalid argument error: must either specify a row count or at least one column
```

Need to wait for next release.

**Comment by viirya** [comment]
Besides, the Java Arrow bus is supported to be fixed in Arrow Java 16. But I still see it happens in a few pipelines:

```
- multiple column distinct count *** FAILED *** (392 milliseconds)
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 59.0 failed 1 times, most recent failure: Lost task 5.0 in stage 59.0 (TID 117) (74d216948a65 executor driver): org.apache.comet.CometNativeException: Fail to process Arrow array with reason C Data interface error: The external buffer at position 2 is null..
```

And more interesting is, the test doesn't always have the failure. I also cannot reproduce it locally.
Wondering if there are more than one Java Arrow jar is included to randomly it picks up an older version. 🤔

**Comment by viirya** [comment]
Hmm, the error is actually different:

```
  Cause: org.apache.comet.CometNativeException: Fail to process Arrow array with reason C Data interface error: The external buffer at position 2 is null..
```

Previously, the fixed one is the buffer at position 1 (offset buffer):

```
General execution error with reason org.apache.comet.CometNativeException: Fail to process Arrow array with reason C Data interface error: The external buffer at position 1 is null...
```

I need to look at what the buffer is at position 2 and why Java Arrow passes a null buffer again...

**Comment by viirya** [comment]
Ah, I found that I made a mistake in the Java Arrow PR that it doesn't initiate the offset buffer well. Proposed another issue at Java Arrow https://github.com/apache/arrow/issues/41609

**Comment by viirya** [comment]
I fixed the issue at arrow-rs in the PR https://github.com/apache/arrow-rs/issues/5756.

We can continue this PR after the fix is released. Keep this as draft for now.

**Comment by viirya** [comment]
I have verified the fix https://github.com/apache/arrow-rs/issues/5756 can work by cherry-picking it in my forked branch of arrow-rs.

**Comment by viirya** [comment]
arrow-rs and DataFusion have fast release cycle. We can hold Comet release after the new releases of arrow-rs and DataFusion.

**Comment by viirya** [comment]
I changed from my forked of DataFusion repo to official DataFusion repo in `Cargo.toml`.

**Comment by viirya** [comment]
@andygrove I can changed to use official DataFusion repo, but cannot do same for arrow-rs repo. The official DataFusion repo uses arrow-rs release 51.0.0. If I point to arrow-rs repo, rust compiler will complain that two different versions of crate of arrow are used.

But we need one merged patch in arrow-rs which is not released yet.

Thus we still need to wait for next arrow-rs and DataFusion releases.

**Comment by viirya** [comment]
Okay. After #511 is fixed, there is only one failures:

```
  Cause: org.apache.comet.CometNativeException: Fail to process Arrow array with reason C Data interface error: The external buffer at position 2 is null..
```

which is known and we already fixed it at the upstream. We only need to wait for next DataFusion and arrow-rs releases that should be happened soon.

**Comment by viirya** [comment]
Using 39.0.0-rc1 tag now.

**Review by kazuyukitanimura — APPROVED** [review]
LGTM pending ci

**Comment by viirya** [comment]
All tests are passed!

**Comment by viirya** [comment]
cc @andygrove

**Review by andygrove — APPROVED** [review]
🎉

**Comment by viirya** [comment]
Thanks @advancedxy @kazuyukitanimura @andygrove

**Pull request merged**
