### PR TITLE
chore: Change maven group ID to `org.apache.datafusion`

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Part of https://github.com/apache/datafusion-comet/issues/721

## Rationale for this change

I am requesting that ASF INFRA sets up Nexus access for the DataFusion project so that we can publish Maven artifacts. The normal convention for maven group ids for Apache projects is `org.apache.TLPNAME`, so I think we need to revisit changing our Maven group ids (<groupId> in the pom.xml) from `org.apache.comet` to `org.apache.datafusion`. The DataFusion project could hypothetically want to publish Java bindings to Maven in the future as well. The artifact names would not change and there is no need to change package names in the code.

Note that we did previously discuss this back in https://github.com/apache/datafusion-comet/pull/278.

### CODE REVIEW

**Comment by parthchandra** [comment]
@huaxingao  This will presumably affect the dependency in iceberg that we are proposing to add.

**Comment by parthchandra** [comment]
@andygrove the previous discussion on this is still relevant (I don't have a strong opinion on this). 
is it still possible for the DataFusion project to publish to multiple maven group ids or does the Nexus repository setup only allow a single group id per project.

**Comment by andygrove** [comment]
> @andygrove the previous discussion on this is still relevant (I don't have a strong opinion on this). is it still possible for the DataFusion project to publish to multiple maven group ids or does the Nexus repository setup only allow a single group id per project.

I had a brief discussion with ASF infra and they said that the Maven group ID should be `org.apache.TLPNAME` although there are exceptions to that. If we want to use a different TLPNAME then I think we will need to have a conversation with ASF infra to request an exception.

**Comment by parthchandra** [comment]
> I had a brief discussion with ASF infra and they said that the Maven group ID should be `org.apache.TLPNAME`

Well, that settles it then.

**Review by parthchandra — APPROVED** [review]
lgtm

**Comment by huaxingao** [comment]
> This will presumably affect the dependency in iceberg that we are proposing to add.

@parthchandra Do I need to change anything on iceberg side?

**Review by huaxingao — APPROVED** [review]
LGTM

**Comment by parthchandra** [comment]
> > This will presumably affect the dependency in iceberg that we are proposing to add.
> 
> @parthchandra Do I need to change anything on iceberg side?

The dependency will change from `org.apache.comet:comet-spark` to `org.apache.datafusion:comet-spark` etc

**Pull request merged**
