### PR TITLE
chore: Don't transform the HashAggregate to CometHashAggregate if Comet shuffle is disabled

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Do the benchmarks in https://github.com/apache/datafusion-comet/blob/84cccf7dba6be52dc7901c7e7fe47c51a9a5b35a/spark/src/test/scala/org/apache/spark/sql/benchmark/CometAggregateBenchmark.scala#L4 need to be updated? Part of my exploration today (that motivates this PR) is that the CometBaseBenchmark and by extension the CometAggregateBenchmark does not set Comet at the shuffle manager.

**Comment by viirya** [comment]
Yea, we should update CometAggregateBenchmarks to enable shuffle for it.

**Review by kazuyukitanimura — APPROVED** [review]

**Comment by mbutrovich** [comment]
This should help a lot for #987! Thanks for the quick fix!

**Comment by viirya** [comment]
Thanks @kazuyukitanimura @mbutrovich

**Pull request merged**
