### PR TITLE
fix: Reuse previous CometDictionary Java arrays

### LINKED ISSUE #488: Reuse previous `CometDictionary` Java arrays
### Describe the bug

After #474, `ColumnReader.loadVector` initiates `CometDictionary` after re-import arrays. It is reported by @andygrove (https://github.com/apache/datafusion-comet/pull/473#issuecomment-2133964232) that after the patch, there is obvious regression when comparing with Spark.

It is because, although re-importing dictionary values is fast, `CometDictionary` has an initialization step to copy values from imported dictionary values to an internal Java array. We need to re-use previous `CometDictionary`'s copied Java arrays.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #488.

### CODE REVIEW

**Review by kazuyukitanimura — APPROVED** [review]
Pending CI

**Comment by viirya** [comment]
cc @andygrove too

**Comment by viirya** [comment]
Thank you @kazuyukitanimura

**Review by andygrove — APPROVED** [review]
Thanks @viirya

**Comment by viirya** [comment]
Merged. Thanks @andygrove @kazuyukitanimura

**Pull request merged**
