### PR TITLE
fix: rat check error caused by logos

### PR DESCRIPTION
**Pull request by PengleiShi**
## Which issue does this PR close?

fix rat check error
Closes #.

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
Thanks @PengleiShi

**Review by andygrove — CHANGES_REQUESTED** [review]
We don't want to add these files to .gitnore but we need to exclude them from the rat check - there is a rat exclude list and also we have a list in the maven pom.xml

**Comment by parthchandra** [comment]
> there is a rat exclude list and also we have a list in the maven pom.xml

I'm in favor of adding this to the `dev/release/rat_exclude_files.txt` file rather than the maven pom file. 
However, I notice that there is no actual `<excludesFile>`  configuration specified in the pom file. Is this invoked elsewhere (maybe on the command line)?

**Comment by andygrove** [comment]
Fixed in https://github.com/apache/datafusion-comet/pull/709

**Pull request closed without merging**
