### PR TITLE
chore: Use twox-hash 2.0 xxhash64 oneshot api instead of custom implementation

### LINKED ISSUE #1032: Use twox_hash 2.0
### What is the problem the feature request solves?

`twox_hash` 2.0 includes a `oneshot` API which probably removes the need for a custom implementation

### Describe the potential solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NoeB**
## Which issue does this PR close?

Closes #1032 

## What changes are included in this PR?

- Use two-hash 2.0 onshot api instead of custom hash implementation
- Upgrades Rust to 1.81.0 (is required by twox-hash Version 2.0)

### CODE REVIEW

**Comment by NoeB** [comment]
I am unsure if license.txt and Notice.txt also need to be updated 
They got introduced with #575

**Comment by NoeB** [comment]
Cargo Bench results:

```bash
hash/xxhash64/8192      time:   [414.63 µs 415.13 µs 415.67 µs]
                        change: [-6.6364% -6.3063% -5.9526%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe
```

**Comment by andygrove** [comment]
> I am unsure if license.txt and Notice.txt also need to be updated The references regarding the code from twox-hash got introduced with #575

Yes, the twox_hash references should be removed from those files as part of this PR

**Comment by NoeB** [comment]
How should I proceed with the pipeline failure which comes from a new clippy rule (manual_pattern_char_comparison) introduced in 1.81.0? 
Should I apply the suggestion or create a pull request with the upgrade to 1.81.0 and apply it there or do you have a different suggestion?

**Comment by NoeB** [comment]
> > I am unsure if license.txt and Notice.txt also need to be updated The references regarding the code from twox-hash got introduced with #575
> 
> Yes, the twox_hash references should be removed from those files as part of this PR

I have added a new commit which removes the references

**Comment by andygrove** [comment]
> How should I proceed with the pipeline failure which comes from a new clippy rule (manual_pattern_char_comparison) introduced in 1.81.0? Should I apply the suggestion or create a pull request with the upgrade to 1.81.0 and apply it there or do you have a different suggestion?

I think it would be fine to apply the change in this PR.

I checked our policy on which Rust versions we support, and upgrading to 1.81.0 is consistent with that policy.

```
DataFusion's Minimum Required Stable Rust Version (MSRV) policy is to support stable 4 latest Rust versions OR the stable minor Rust version as of 4 months, whichever is lower.
```

**Comment by andygrove** [comment]
I got slightly different cargo bench results, but I saw no regression in overall TPC-H performance.

```
hash/xxhash64/8192      time:   [306.49 µs 307.37 µs 308.27 µs]
                        change: [+5.5768% +5.9235% +6.2740%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

**Comment by NoeB** [comment]
Interesting, I just reran the bench and I get the same improvements as before. Should I compare the library implementation with the DataFusion custom one to see if there is a difference? 

Shall I add the following command to the docs: `cd native && cargo clippy --color=never --all-targets --workspace -- -D warnings` in the [( Submitting a PR section)](https://datafusion.apache.org/comet/contributor-guide/development.html#submitting-a-pull-request)? I think it would have saved me several CI runs.

**Comment by andygrove** [comment]
> Interesting, I just reran the bench and I get the same improvements as before. Should I compare the library implementation with the DataFusion custom one to see if there is a difference?

It is possible that the results could vary depending on hardware. Out of interest what platform are you testing on? I am testing on an AMD Ryzen 9 CPU  with Linux. 

5% is a small price to pay to remove the custom implementation and go back to using the dependency, IMO.
 
> Shall I add the following command to the docs: `cd native && cargo clippy --color=never --all-targets --workspace -- -D warnings` in the [( Submitting a PR section)](https://datafusion.apache.org/comet/contributor-guide/development.html#submitting-a-pull-request)? I think it would have saved me several CI runs.

That would be great as a separate PR, thank you.

**Comment by NoeB** [comment]
Thank you @andygrove for reviewing the PR and starting the CI.
I tested it on an Apple M1 Max running macOS Sequoia.

> That would be great as a separate PR, thank you.

I will do that later

**Pull request merged**
