### PR TITLE
chore: Update Comet repo description

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao @andygrove

**Review by sunchao — APPROVED** [review]

**Comment by sunchao** [comment]
oops I can no longer approve the PRs???

**Comment by viirya** [comment]
DataFusion becomes top-level project now. So Arrow committers cannot approve DataFusion PRs.

**Comment by andygrove** [comment]
> oops I can no longer approve the PRs???

Possibly because the repo moved from Apache Arrow to Apache DataFusion project?

**Review by andygrove — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.

**Comment by sunchao** [comment]
Hmm I thought I'm also in the initial committer list for DataFusion 😂

**Comment by viirya** [comment]
> Hmm I thought I'm also in the initial committer list for DataFusion 😂

I think the plan is add Arrow PMCs who are willing to be DataFusion PMCs as initial PMCs and committers. Original committers will be added later.

**Pull request merged**
